version: "3.9"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  migration:
    build: .
    command: python manage.py migrate
    volumes:
      - .:/code
    depends_on:
      - db
  static:
    build: .
    command: python manage.py collectstatic
    volumes:
      - .:/code
    depends_on:
      - migration
      - db
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - static
      - migration
      - db

